import Link from 'next/link';
import { CreditCard, MessageCircle, ShieldCheck, Tag } from 'lucide-react';
import { PublicLayout } from '@/components/public/PublicLayout';
import { Container } from '@/components/shared/Container';
import { SectionHeader } from '@/components/public/SectionHeader';
import { createClient } from '@/lib/supabase/server';
import { formatPKR } from '@/lib/utils';
export default async function FeesPage(){const supabase=await createClient();const{data:a}=await supabase.from('academy_settings').select('*').eq('status','active').limit(1).maybeSingle();const{data:classData}=a?await supabase.from('classes').select('*').eq('academy_id',a.id).eq('status','active').order('class_name'):{data:[]};const fee=Number(a?.default_monthly_fee||3000);const classes=Array.isArray(classData)&&classData.length?classData:[{class_name:'9th / 10th',default_monthly_fee:fee,description:'Matric classes'},{class_name:'FSC',default_monthly_fee:fee,description:'Intermediate classes'},{class_name:'Computer / English',default_monthly_fee:fee,description:'Short courses'}];return <PublicLayout><main><section className="bg-gradient-to-br from-blue-50 via-white to-slate-100 py-20"><Container><SectionHeader eyebrow="Fee Structure" title="Simple monthly fee information for parents" description="Exact fee class/course, batch aur discount policy ke hisaab se vary kar sakti hai. Latest details ke liye AI chat ya academy contact use karein." center/></Container></section><section className="py-20"><Container><div className="grid gap-5 md:grid-cols-3">{classes.map((item:any)=><div key={item.id||item.class_name} className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="grid h-13 w-13 place-items-center rounded-2xl bg-blue-50 text-blue-600"><CreditCard size={25}/></div><p className="mt-5 text-sm font-black uppercase tracking-wide text-slate-500">Program</p><h2 className="mt-2 text-2xl font-black text-slate-950">{item.class_name}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{item.description||'Monthly fee class/course ke hisaab se manage hoti hai.'}</p><p className="mt-5 text-3xl font-black text-blue-700">{formatPKR(Number(item.default_monthly_fee||fee))}</p><p className="mt-2 text-xs font-semibold text-slate-500">Monthly fee estimate</p></div>)}</div><div className="mt-10 grid gap-5 lg:grid-cols-3"><Info icon={ShieldCheck} title="Transparent process" text="Fee slip, paid amount, pending balance aur monthly records admin panel mein track hote hain."/><Info icon={Tag} title="Discount policy" text="Discount fixed nahi hai. Discount ke liye academy admin se confirm karna hoga."/><Info icon={MessageCircle} title="Ask AI chat" text="Website ke AI chat se fee, timing, admission process aur address pooch sakte hain." green/></div><div className="mt-10 rounded-[2rem] border border-blue-200 bg-blue-50 p-8 text-center"><h3 className="text-2xl font-black text-slate-950">Need exact fee confirmation?</h3><p className="mt-3 text-sm text-slate-700">Class/course select karne ke baad academy office se latest fee and discount details confirm karein.</p><Link href="/contact" className="mt-6 inline-flex rounded-2xl bg-blue-600 px-5 py-3 text-sm font-black text-white hover:bg-blue-700">Contact Academy</Link></div></Container></section></main></PublicLayout>}
function Info({icon:Icon,title,text,green=false}:any){return <div className={green?'rounded-[2rem] border border-emerald-200 bg-emerald-50 p-6 shadow-sm':'rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm'}><Icon className={green?'text-emerald-600':'text-blue-600'} size={32}/><h3 className={green?'mt-4 text-xl font-black text-emerald-950':'mt-4 text-xl font-black text-slate-950'}>{title}</h3><p className={green?'mt-2 text-sm leading-7 text-emerald-900':'mt-2 text-sm leading-7 text-slate-600'}>{text}</p></div>}
