'use client';
import { FormEvent, useRef, useState } from 'react';
import { Bot, MessageCircle, Send, X } from 'lucide-react';
type Message = { role: 'user' | 'assistant'; content: string };
const welcome: Message[] = [{ role: 'assistant', content: 'Assalam-o-Alaikum! Fees, timings, teachers, admission process ya location ke bare mein pooch sakte hain.' }];
export function LiveChatWidget() {
  const [open,setOpen] = useState(false); const [input,setInput]=useState(''); const [loading,setLoading]=useState(false); const [messages,setMessages]=useState<Message[]>(welcome); const inputRef=useRef<HTMLInputElement|null>(null);
  async function sendMessage(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const text=input.trim(); if(!text||loading)return; const next=[...messages,{role:'user' as const,content:text}]; setMessages(next); setInput(''); setLoading(true); try { const response=await fetch('/api/public-ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,history:messages.slice(-8)})}); const data=await response.json(); if(!response.ok) throw new Error(data?.error||'AI reply generate nahi ho saka.'); setMessages([...next,{role:'assistant',content:data?.reply||'Ye detail abhi available nahi hai, academy se confirm karna hoga.'}]); } catch(error:any){ setMessages([...next,{role:'assistant',content:error?.message||'AI abhi busy hai. Please thori der baad try karein.'}]); } finally { setLoading(false); setTimeout(()=>inputRef.current?.focus(),100); }}
  if(!open) return <button onClick={()=>setOpen(true)} className="fixed bottom-5 right-5 z-50 grid h-14 w-14 place-items-center rounded-full bg-blue-600 text-white shadow-2xl shadow-blue-900/30 transition hover:scale-105 hover:bg-blue-700" aria-label="Open AI chat"><MessageCircle size={25}/><span className="absolute right-1 top-1 h-3.5 w-3.5 rounded-full border-2 border-white bg-emerald-400"/></button>;
  return <div className="fixed bottom-5 right-5 z-50 flex h-[560px] w-[calc(100vw-2rem)] max-w-md flex-col overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-2xl shadow-slate-900/25"><div className="flex items-center justify-between bg-blue-600 px-5 py-4 text-white"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-white/15"><Bot size={21}/></span><div><p className="text-sm font-black">AI Admission Assistant</p><p className="text-xs text-blue-100">Online • instant academy information</p></div></div><button onClick={()=>setOpen(false)} className="rounded-xl p-2 hover:bg-white/10" aria-label="Close chat"><X size={20}/></button></div><div className="flex-1 space-y-3 overflow-y-auto bg-slate-50 p-4">{messages.map((m,i)=><div key={i} className={m.role==='user'?'flex justify-end':'flex justify-start'}><div className={m.role==='user'?'max-w-[82%] rounded-2xl bg-blue-600 px-4 py-3 text-sm leading-6 text-white shadow-sm':'max-w-[82%] rounded-2xl bg-white px-4 py-3 text-sm leading-6 text-slate-800 shadow-sm'}>{m.content}</div></div>)}{loading?<div className="flex justify-start"><div className="rounded-2xl bg-white px-4 py-3 text-sm text-slate-500 shadow-sm">Typing...</div></div>:null}</div><form onSubmit={sendMessage} className="flex gap-2 border-t bg-white p-3"><input ref={inputRef} value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask fee, timing, teachers..." className="min-w-0 flex-1 rounded-2xl border border-slate-300 px-4 py-3 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100"/><button disabled={loading} className="grid h-12 w-12 place-items-center rounded-2xl bg-blue-600 text-white hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-60" aria-label="Send"><Send size={18}/></button></form></div>;
}
